Disable old PRYYSM-2 workflow - incorrect app name
Issue: GitHub Actions workflow 'main_pryysm-2.yml' was configured to deploy to 'PRYYSM-2' Azure app which doesn't exist
Error: 'Resource PRYYSM-2 of type Microsoft.Web/Sites doesn't exist'

Solution: Disabled main_pryysm-2.yml - renamed to .disabled extension
         Only main_pryysm-v2.yml will run - deploys to correct 'PRYYSM-V2' app

Now deployment will:
 Use correct workflow: main_pryysm-v2.yml
 Deploy to correct app: PRYYSM-V2
 Use correct database provider: sqlserver
 Login/signup should work on pryysm.app